### ISSUE TITLE
Selenium Functionality

### ISSUE THREAD

**Issue by Yoorbo** [Yoorbo/owl-watch#1]

**Comment by RobertoCarlosMedina** [comment]
I'm here to ask something because e have a little problem, 
Taking in mind that I'm using Linux as OS, my selenium doesn't upload the images that I tell the program to upload.
in the code it said's that the image was upload but in the site I have no images.
Can you help me?

**Comment by Yoorbo** [comment]
> I'm here to ask something because e have a little problem, 
> Taking in mind that I'm using Linux as OS, my selenium doesn't upload the images that I tell the program to upload.
> in the code it said's that the image was upload but in the site I have no images.
> Can you help me? 

I dont think that I can help you properly. Though I know how to work with Selenium, I am lacking enough information. What Site, whats your code, whats its purpose? Greets :)
